#!/usr/bin/env bash

keepBuildingDarwin() {
    (( counter_darwin++ ))
    sudo darwin-rebuild switch --flake . || keepBuilding
}

keepBuildingHome() {
    (( counter_hm++))
    home-manager --flake . switch || keepBuildingHome
}


counter_darwin=0
counter_hm=0
keepBuildingDarwin
keepBuildingHome

echo "built darwin in ${counter_darwin} iterations"
echo "built home   in ${counter_hm} iterations"
