#!/usr/bin/env bash

download_nixpkgs_cache_index () {
        location=~/.cache/nix-index
        filename="index-$(uname -m | sed 's/^arm64$/aarch64/')-$(uname | tr '[:upper:]' '[:lower:]')"
        mkdir -p "$location"
        wget -P "$location" -q -N "https://github.com/nix-community/nix-index-database/releases/latest/download/$filename"
        ln -f "$location/$filename" "$location/files"
}

# Flake update
nix flake update && git commit -m 'update flake.lock' flake.lock && git push


nix-collect-garbage -d
sudo nix-collect-garbage -d

# use keepbuilding script to work around issues
./keepBuilding

nix flake archive
download_nixpkgs_cache_index
