#!/usr/bin/env bash

download_nixpkgs_cache_index () {
        location=~/.cache/nix-index
        filename="index-$(uname -m | sed 's/^arm64$/aarch64/')-$(uname | tr A-Z a-z)"
        mkdir -p "$location"
        wget -P "$location" -q -N https://github.com/nix-community/nix-index-database/releases/latest/download/$filename
        ln -f "$location/$filename" "$location/files"
}

nix flake update && git commit -m 'update flake.lock' flake.lock

# use keepbuilding script to work around issues
./keepBuilding

nix flake archive
download_nixpkgs_cache_index

git push 
